PLEASE REFER TO APPENDIX ON HOW TO RUN THE CODE, CHANGE THE FILE NAMES ACCORDINGLY IN ORDER FOR THE DATASETS TO BE IMPORTED ON YOUR SYSTEM. YOU CAN LOCATE THE WHEREABOUTS OF THE CSV'S BY CHECKING THE PATHWAY WHERE THE CODE IS TRYING TO IMPORT

USE localized_url function if there's an error with the imports

In [ ]:
import os
def localized_url(url):

    current_dir = os.getcwd().split("statistical-analysis-and-modeling-of-football-data")[0] + "statistical-analysis-and-modeling-of-football-data"
    branch = url.split("statistical-analysis-and-modeling-of-football-data")[1]
    return current_dir + branch

In [2]:
import numpy as np
import pandas as pd
import re
import time
import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium_stealth import stealth
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import logging
import functools

In [3]:
url="https://www.fifaindex.com/teams/fifa19/?league=13&order=desc"
response = requests.get(url)
if response.status_code == 200:
    print("Successfully fetched the page")
else:
    print(f"Failed to fetch the page, status code: {response.status_code}")

Failed to fetch the page, status code: 403

In [20]:

# Clear existing handlers
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

In [3]:

def retry(max_attempts=3, delay=3, exceptions=(Exception,), logger=None):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            attempts = 0
            while attempts < max_attempts:
                try:
                    return func(*args, **kwargs)
                except exceptions as e:
                    attempts += 1
                    if logger:
                        logger.warning(f"Attempt {attempts} failed for {func.__name__}: {e}")
                    else:
                        print(f"Attempt {attempts} failed for {func.__name__}: {e}")
                    if attempts == max_attempts:
                        if logger:
                            logger.error(f"{func.__name__} failed after {max_attempts} attempts.")
                        raise
                    time.sleep(delay)
        return wrapper
    return decorator

In [4]:
def initialize_driver():
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument("--start-maximized")


    driver = webdriver.Chrome(options=options)

    stealth(driver,
            languages=["en-US", "en"],
            vendor="Google Inc.",
            platform="Win32",
            webgl_vendor="Intel Inc.",
            renderer="Intel Iris OpenGL Engine",
            fix_hairline=True)
    
    return driver

In [5]:
@retry(max_attempts=3, delay=5, exceptions=(Exception,), logger=logging)
def scrape_sofifa_player_stats(url, team_name, version):
    driver = initialize_driver()
    driver.get(url)

    # Accept cookies via shadow DOM
    try:
        shadow_host = driver.find_element(By.CSS_SELECTOR, "#cmpwrapper")
        shadow_root = driver.execute_script("return arguments[0].shadowRoot", shadow_host)
        accept_button = shadow_root.find_element(By.CSS_SELECTOR, "#cmpwelcomebtnyes")
        accept_button.click()
        time.sleep(1)
    except Exception as e:
        logging.warning(f"Could not interact with cookie popup on {url}: {e}")
    

    # Wait for stat cards
    WebDriverWait(driver, 10).until(
        EC.presence_of_all_elements_located((By.CLASS_NAME, "card"))
    )

    desired_categories = {
        "Ball Skills", "Passing", "Shooting", "Defence",
        "Physical", "Mental", "Goalkeeper"
    }

    player_stats = {}
    cards = driver.find_elements(By.CLASS_NAME, "card")

    for card in cards:
        try:
            category = card.find_element(By.CLASS_NAME, "card-header").text.strip()
            if category not in desired_categories:
                continue
            body = card.find_element(By.CLASS_NAME, "card-body")
            p_tags = body.find_elements(By.TAG_NAME, "p")
            for p in p_tags:
                stat_name = p.text.split('\n')[0].strip()
                stat_value = p.find_element(By.CLASS_NAME, "float-right").text.strip()
                player_stats[stat_name] = stat_value
        except Exception as e:
            logging.warning(f"Skipping a stat card due to error: {e}")
            continue

    df = pd.DataFrame(player_stats, columns=player_stats.keys(), index=[0])
    df['Team'] = team_name
    df['Version'] = version
    driver.quit()
    return df

In [6]:
@retry(max_attempts=3, delay=5, exceptions=(Exception,), logger=logging)
def get_team_links_df(url,version):
    driver = initialize_driver()

    driver.get(url)

    # Accept cookies via shadow DOM
    try:
        shadow_host = driver.find_element(By.CSS_SELECTOR, "#cmpwrapper")
        shadow_root = driver.execute_script("return arguments[0].shadowRoot", shadow_host)
        accept_button = shadow_root.find_element(By.CSS_SELECTOR, "#cmpwelcomebtnyes")
        accept_button.click()
        time.sleep(1)
    except Exception as e:
        logging.warning(f"Could not interact with cookie popup on {url}: {e}")

    # Scrape team links and names
    team_links = driver.find_elements(By.CSS_SELECTOR, "table.table-teams a.link-team")
    team_data = set()
    for link in team_links:
        name = link.text.strip()
        href = link.get_attribute("href")
        if name and href:
            team_data.add((name, href))  # Use set to avoid duplicates



    # Convert to DataFrame
    df = pd.DataFrame(sorted(team_data), columns=["Team Name", "Team URL"])
    df["Version"] = version
    driver.quit()
    logging.info(f"Extracted {len(df)} teams from {url} with version {df['Version'].iloc[0]}")
    return df

In [7]:
@retry(max_attempts=3, delay=5, exceptions=(Exception,), logger=logging)
def get_player_links(url, team_name):
    # Setup driver
    driver = initialize_driver()

    driver.get(url)

    # Accept cookies via shadow DOM
    try:
        shadow_host = driver.find_element(By.CSS_SELECTOR, "#cmpwrapper")
        shadow_root = driver.execute_script("return arguments[0].shadowRoot", shadow_host)
        accept_button = shadow_root.find_element(By.CSS_SELECTOR, "#cmpwelcomebtnyes")
        accept_button.click()
        time.sleep(1)
    except Exception as e:
        logging.warning(f"Could not interact with cookie popup on {url}: {e}")
        logging.warning("Retrying with cookies visa shadow DOM interaction")
        time.sleep(5)
        try:
            shadow_host = driver.find_element(By.CSS_SELECTOR, "#cmpwrapper")
            shadow_root = driver.execute_script("return arguments[0].shadowRoot", shadow_host)
            accept_button = shadow_root.find_element(By.CSS_SELECTOR, "#cmpwelcomebtnyes")
            accept_button.click()
            time.sleep(1)
        except Exception as e:
            logging.error(f"Failed to accept cookies after retrying: {e}")
            logging.error("Retrying without cookie acceptance")
            try:
                accept_button = driver.find_element(By.CSS_SELECTOR, "#cmpwelcomebtnyes")
                accept_button.click()
                time.sleep(1)
            except Exception as e:
                logging.error(f"Failed to accept cookies without shadow DOM: {e}")
                

    # Extract data early to avoid stale references
    elements = driver.find_elements(By.CSS_SELECTOR, "table.table-players a.link-player")
    player_data = {
        (el.text.strip(), el.get_attribute("href")) for el in elements
        if el.text.strip() and el.get_attribute("href")
    }

    df = pd.DataFrame(sorted(player_data), columns=["Player Name", "Player URL"])
    df["Team Name"] = team_name
    df["Version"] = url.rstrip('/').split('/')[-1]
    driver.quit()
    logging.info(f"Extracted {len(df)} players from {team_name} with version {df['Version'].iloc[0]}")
    return df

In [8]:
@retry(max_attempts=3, delay=5, exceptions=(Exception,), logger=logging)
def get_player_stats_from_team(team_df):
    player_stats = pd.DataFrame()

    for index, row in team_df.iterrows():
        player_url = row['Player URL']
        player_name = row['Player Name']
        logging.info(f"Scraping stats for {player_name} from {player_url}...")

        try:
            stats_df = scrape_sofifa_player_stats(player_url, row["Team Name"], row["Version"])  # Should return a DataFrame
            stats_df.insert(0, 'Player Name', player_name)     # Add name as first column
            player_stats = pd.concat([player_stats, stats_df], ignore_index=True)
            

        except Exception as e:
            logging.error(f"Error scraping {player_name}: {e}")
            logging.error("Retrying with a new driver instance")
            try:
                stats_df = scrape_sofifa_player_stats(player_url, row["Team Name"], row["Version"])  # Should return a DataFrame
                stats_df.insert(0, 'Player Name', player_name)     # Add name as first column
                player_stats = pd.concat([player_stats, stats_df], ignore_index=True)
            except Exception as e:
                logging.error(f"Failed to scrape stats for {player_name} after retry: {e}")
                continue
        else:
            logging.info(f"Successfully scraped stats for {player_name} from  team {row['Team Name']} , version {row['Version']}")
    
        

    return player_stats

#Lets create a big data frame with all players from all teams from all seasons
# To create a progress bar, we can use tqdm
from tqdm import tqdm
fifa_years_list = [i for i in range(16, 25)]
season_urls_list=["https://www.fifaindex.com/teams/fifa"+str(i)+"/?league=13&order=desc" for i in fifa_years_list]

all_teams_df = pd.DataFrame()
for url in tqdm(season_urls_list, desc="Gathering team links"):
    teams_df = get_team_links_df(url)
    all_teams_df = pd.concat([all_teams_df, teams_df], ignore_index=True)
# -- Step 2: Get all teams
all_teams_df = pd.DataFrame()
for url in tqdm(season_urls_list, desc="Gathering team links"):
    teams_df = get_team_links_df(url)
    all_teams_df = pd.concat([all_teams_df, teams_df], ignore_index=True)

# Now we have all players from all teams from all seasons, we can scrape their stats
# We can use the get_player_stats_from_team function to scrape the stats for each team

all_player_stats_df = pd.DataFrame()
for index, row in tqdm(all_players_df.iterrows(), total=len(all_players_df), desc="Gathering player stats"):
    team_name = row['Team Name']
    version = row['Version']
    team_stats_df = get_player_stats_from_team(all_players_df[all_players_df['Team Name'] == team_name])
    all_player_stats_df = pd.concat([all_player_stats_df, team_stats_df], ignore_index=True)

In [35]:
import pandas as pd
import time
import logging
from tqdm import tqdm
from pathlib import Path

# Setup logging
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(
    filename='scraper.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filemode='a'
)
logging.info("--------------------------Setting up logging---------------------------")
# -- Step 1: Define URLs
fifa_years_dict = {}

for i in range(16, 25):
    fifa_years_dict[i] = f"https://www.fifaindex.com/teams/fifa{i}/?league=13&order=desc"
fifa_years_list = list(fifa_years_dict.keys())

# -- Step 2: Get all teams
all_teams_df = pd.DataFrame()
for i in tqdm(fifa_years_list, desc="Gathering team links"):
    url = fifa_years_dict[i]
    try:
        teams_df = get_team_links_df(url, f"fifa{i}")
        all_teams_df = pd.concat([all_teams_df, teams_df], ignore_index=True)
        time.sleep(1.5)
    except Exception as e:
        logging.error(f"❌ Error gathering teams for FIFA {i}: {e}")
        time.sleep(5)
        try:
            teams_df = get_team_links_df(url, f"fifa{i}")
            all_teams_df = pd.concat([all_teams_df, teams_df], ignore_index=True)
            time.sleep(1.5)
            logging.info(f"✅ Retry successful for FIFA {i}")
        except Exception as e2:
            logging.error(f"❌ Retry failed for FIFA {i}: {e2}")
            continue

# -- Step 3: Get all players
all_players_df = pd.DataFrame()
for index, row in tqdm(all_teams_df.iterrows(), total=len(all_teams_df), desc="Gathering player links"):
    team_url = row['Team URL']
    team_name = row['Team Name']
    try:
        players_df = get_player_links(team_url, team_name)
        all_players_df = pd.concat([all_players_df, players_df], ignore_index=True)
    except Exception as e:
        logging.error(f"Error gathering players for {team_name}: {e}")

# Save intermediate checkpoint
all_players_df.to_csv("all_players_checkpoint.csv", index=False)

# -- Step 4: Scrape Player Stats with Team-Level Efficiency

# Load progress if exists
checkpoint_path = Path("all_player_stats_checkpoint.csv")
if checkpoint_path.exists():
    all_player_stats_df = pd.read_csv(checkpoint_path)
    scraped_teams = set(zip(all_player_stats_df['Team'], all_player_stats_df['Version']))
else:
    all_player_stats_df = pd.DataFrame()
    scraped_teams = set()

# Group players by (team_name, version)
grouped_teams = all_players_df.groupby(['Team Name', 'Version'])

# Scrape each team only once
for (team_name, version), group in tqdm(grouped_teams, desc="Scraping team stats"):
    if (team_name, version) in scraped_teams:
        continue

    try:
        stats_df = get_player_stats_from_team(group)
        all_player_stats_df = pd.concat([all_player_stats_df, stats_df], ignore_index=True)

        # Save progress
        all_player_stats_df.to_csv("all_player_stats_checkpoint.csv", index=False)
        logging.info(f"✅ Scraped stats for {team_name} ({version})")

    except Exception as e:
        logging.error(f"❌ Failed scraping for {team_name} ({version}): {e}")
        continue

# Final save
all_player_stats_df.to_csv("all_player_stats_final.csv", index=False)
logging.info("✅ Scraping completed and final dataset saved.")

Gathering team links: 100%|██████████| 9/9 [00:50<00:00,  5.57s/it]
Gathering player links: 100%|██████████| 180/180 [18:27<00:00,  6.15s/it]
Scraping team stats: 100%|██████████| 180/180 [10:11:54<00:00, 203.97s/it]

In [85]:
all_player_stats_df = pd.read_csv("all_player_stats_final.csv")

In [86]:
all_player_stats_df

,Player Name,Ball Control,Dribbling,Marking,Slide Tackle,Stand Tackle,Aggression,Reactions,Att. Position,Interceptions,...,Volleys,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes,Team,Version,Stamina 6,Sprint Speed 1
0,Adam Smith,74.0,68.0,NaN,74.0,75.0,73.0,73.0,65.0,69.0,...,43.0,9.0,8.0,9.0,15.0,6.0,AFC Bournemouth,afc-bournemouth,NaN,NaN
1,Antoine Semenyo,69.0,72.0,NaN,11.0,19.0,62.0,68.0,68.0,14.0,...,56.0,15.0,10.0,11.0,14.0,7.0,AFC Bournemouth,afc-bournemouth,NaN,NaN
2,Chris Mepham,64.0,58.0,NaN,72.0,74.0,73.0,68.0,39.0,71.0,...,33.0,14.0,10.0,10.0,12.0,12.0,AFC Bournemouth,afc-bournemouth,NaN,NaN
3,Dango Ouattara,74.0,78.0,NaN,44.0,51.0,46.0,66.0,74.0,52.0,...,49.0,14.0,9.0,6.0,13.0,10.0,AFC Bournemouth,afc-bournemouth,NaN,NaN
4,Darren Randolph,33.0,14.0,NaN,14.0,14.0,29.0,70.0,11.0,18.0,...,16.0,70.0,74.0,70.0,66.0,73.0,AFC Bournemouth,afc-bournemouth,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7387,Ryan Giles,67.0,68.0,NaN,62.0,66.0,55.0,62.0,50.0,56.0,...,41.0,8.0,14.0,6.0,5.0,8.0,Wolves,fifa23,NaN,NaN
7388,Rúben Neves,82.0,75.0,NaN,77.0,79.0,82.0,81.0,62.0,80.0,...,82.0,8.0,16.0,12.0,10.0,10.0,Wolves,fifa23,NaN,NaN
7389,Saša Kalajdžić,78.0,74.0,NaN,47.0,46.0,44.0,78.0,81.0,34.0,...,73.0,14.0,7.0,6.0,13.0,15.0,Wolves,fifa23,NaN,NaN
7390,Theo Corbeanu,66.0,71.0,NaN,45.0,49.0,40.0,57.0,61.0,39.0,...,50.0,10.0,7.0,6.0,9.0,7.0,Wolves,fifa23,NaN,NaN
7391,Toti Gomes,62.0,58.0,NaN,73.0,73.0,72.0,72.0,56.0,74.0,...,42.0,5.0,11.0,6.0,12.0,10.0,Wolves,fifa23,NaN,NaN

In [9]:
def nan_analysis(df):
    """
    This function takes a DataFrame and returns a DataFrame with the percentage of NaN values for each column.
    Only columns with NaN values are included in the output DataFrame.
    """
    nan_percentage = df.isna().mean() * 100
    nan_number = df.isna().sum()
    nan_percentage = nan_percentage[nan_percentage > 0].reset_index()
    nan_number = nan_number[nan_number > 0].reset_index()
    nan_percentage.columns = ['Column', 'Percentage of NaN Values']
    nan_number.columns = ['Column', 'Number of NaN Values']
    nan_percentage = pd.merge(nan_percentage, nan_number, on='Column')
    nan_percentage = nan_percentage.sort_values(by='Percentage of NaN Values', ascending=False)
    return nan_percentage

In [88]:
nan_analysis(all_player_stats_df)

            Column  Percentage of NaN Values  Number of NaN Values
35  Sprint Speed 1                 99.986472                  7391
34       Stamina 6                 99.986472                  7391
2          Marking                 21.415043                  1583
10       Composure                 11.295996                   835
22      Shot Power                  0.798160                    59
23       Finishing                  0.798160                    59
24      Long Shots                  0.798160                    59
25           Curve                  0.798160                    59
26         FK Acc.                  0.798160                    59
27       Penalties                  0.798160                    59
28         Volleys                  0.798160                    59
29  GK Positioning                  0.798160                    59
30       GK Diving                  0.798160                    59
31     GK Handling                  0.798160                    59
32      GK Kicking                  0.798160                    59
33     GK Reflexes                  0.798160                    59
21         Heading                  0.784632                    58
20         Jumping                  0.744048                    55
19         Agility                  0.730519                    54
18    Sprint Speed                  0.730519                    54
17         Balance                  0.716991                    53
15         Stamina                  0.689935                    51
16        Strength                  0.676407                    50
14    Acceleration                  0.649351                    48
13       Long Pass                  0.595238                    44
12      Short Pass                  0.568182                    42
11        Crossing                  0.554654                    41
9           Vision                  0.419372                    31
8    Interceptions                  0.378788                    28
7    Att. Position                  0.311147                    23
6        Reactions                  0.297619                    22
5       Aggression                  0.284091                    21
4     Stand Tackle                  0.189394                    14
3     Slide Tackle                  0.189394                    14
1        Dribbling                  0.121753                     9
0     Ball Control                  0.094697                     7

In [89]:
all_player_stats_df = all_player_stats_df.drop(columns=['Sprint Speed 1', 'Stamina 6'])

In [90]:
# Get the players who have nan values in their stats
players_with_nan = all_player_stats_df[all_player_stats_df.isna().any(axis=1)]
players_with_nan

,Player Name,Ball Control,Dribbling,Marking,Slide Tackle,Stand Tackle,Aggression,Reactions,Att. Position,Interceptions,...,FK Acc.,Penalties,Volleys,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes,Team,Version
0,Adam Smith,74.0,68.0,NaN,74.0,75.0,73.0,73.0,65.0,69.0,...,66.0,55.0,43.0,9.0,8.0,9.0,15.0,6.0,AFC Bournemouth,afc-bournemouth
1,Antoine Semenyo,69.0,72.0,NaN,11.0,19.0,62.0,68.0,68.0,14.0,...,39.0,51.0,56.0,15.0,10.0,11.0,14.0,7.0,AFC Bournemouth,afc-bournemouth
2,Chris Mepham,64.0,58.0,NaN,72.0,74.0,73.0,68.0,39.0,71.0,...,35.0,44.0,33.0,14.0,10.0,10.0,12.0,12.0,AFC Bournemouth,afc-bournemouth
3,Dango Ouattara,74.0,78.0,NaN,44.0,51.0,46.0,66.0,74.0,52.0,...,55.0,66.0,49.0,14.0,9.0,6.0,13.0,10.0,AFC Bournemouth,afc-bournemouth
4,Darren Randolph,33.0,14.0,NaN,14.0,14.0,29.0,70.0,11.0,18.0,...,14.0,30.0,16.0,70.0,74.0,70.0,66.0,73.0,AFC Bournemouth,afc-bournemouth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7387,Ryan Giles,67.0,68.0,NaN,62.0,66.0,55.0,62.0,50.0,56.0,...,67.0,49.0,41.0,8.0,14.0,6.0,5.0,8.0,Wolves,fifa23
7388,Rúben Neves,82.0,75.0,NaN,77.0,79.0,82.0,81.0,62.0,80.0,...,81.0,76.0,82.0,8.0,16.0,12.0,10.0,10.0,Wolves,fifa23
7389,Saša Kalajdžić,78.0,74.0,NaN,47.0,46.0,44.0,78.0,81.0,34.0,...,47.0,57.0,73.0,14.0,7.0,6.0,13.0,15.0,Wolves,fifa23
7390,Theo Corbeanu,66.0,71.0,NaN,45.0,49.0,40.0,57.0,61.0,39.0,...,64.0,55.0,50.0,10.0,7.0,6.0,9.0,7.0,Wolves,fifa23
7391,Toti Gomes,62.0,58.0,NaN,73.0,73.0,72.0,72.0,56.0,74.0,...,48.0,45.0,42.0,5.0,11.0,6.0,12.0,10.0,Wolves,fifa23

In [91]:
# Show all rows that doesn't have "fifa" in the Version column
all_player_stats_df[~all_player_stats_df['Version'].str.contains("fifa", case=False, na=False)]["Version"]
# Change these to fifa24
all_player_stats_df.loc[~all_player_stats_df['Version'].str.contains("fifa", case=False, na=False), 'Version'] = "fifa24"

In [92]:
# Same procedure for all_players_df
all_players_df.loc[~all_players_df['Version'].str.contains("fifa", case=False, na=False), 'Version'] = "fifa24"

In [93]:
all_players_df.columns

Index(['Player Name', 'Player URL', 'Team Name', 'Version'], dtype='object')

In [94]:
# The team name column in all_player_stats_df is not consistent with all_players_df
# Let's rename the 'Team' column in all_player_stats_df to 'Team Name'
all_player_stats_df.rename(columns={'Team': 'Team Name'}, inplace=True)
all_player_stats_df.columns

Index(['Player Name', 'Ball Control', 'Dribbling', 'Marking', 'Slide Tackle',
       'Stand Tackle', 'Aggression', 'Reactions', 'Att. Position',
       'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short Pass',
       'Long Pass', 'Acceleration', 'Stamina', 'Strength', 'Balance',
       'Sprint Speed', 'Agility', 'Jumping', 'Heading', 'Shot Power',
       'Finishing', 'Long Shots', 'Curve', 'FK Acc.', 'Penalties', 'Volleys',
       'GK Positioning', 'GK Diving', 'GK Handling', 'GK Kicking',
       'GK Reflexes', 'Team Name', 'Version'],
      dtype='object')

In [95]:
#Now lets merge the two DataFrames on team name, version and player name so that we can get the url for each player
merged_with_url = pd.merge(all_player_stats_df, all_players_df, 
                               on=['Player Name', 'Team Name', 'Version'],
                               how='left')

In [96]:
players_with_nan=nan_analysis(merged_with_url)

In [97]:
merged_with_url

,Player Name,Ball Control,Dribbling,Marking,Slide Tackle,Stand Tackle,Aggression,Reactions,Att. Position,Interceptions,...,Penalties,Volleys,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes,Team Name,Version,Player URL
0,Adam Smith,74.0,68.0,NaN,74.0,75.0,73.0,73.0,65.0,69.0,...,55.0,43.0,9.0,8.0,9.0,15.0,6.0,AFC Bournemouth,fifa24,https://www.fifaindex.com/player/190885/adam-s...
1,Antoine Semenyo,69.0,72.0,NaN,11.0,19.0,62.0,68.0,68.0,14.0,...,51.0,56.0,15.0,10.0,11.0,14.0,7.0,AFC Bournemouth,fifa24,https://www.fifaindex.com/player/241236/antoin...
2,Chris Mepham,64.0,58.0,NaN,72.0,74.0,73.0,68.0,39.0,71.0,...,44.0,33.0,14.0,10.0,10.0,12.0,12.0,AFC Bournemouth,fifa24,https://www.fifaindex.com/player/233201/chris-...
3,Dango Ouattara,74.0,78.0,NaN,44.0,51.0,46.0,66.0,74.0,52.0,...,66.0,49.0,14.0,9.0,6.0,13.0,10.0,AFC Bournemouth,fifa24,https://www.fifaindex.com/player/265552/dango-...
4,Darren Randolph,33.0,14.0,NaN,14.0,14.0,29.0,70.0,11.0,18.0,...,30.0,16.0,70.0,74.0,70.0,66.0,73.0,AFC Bournemouth,fifa24,https://www.fifaindex.com/player/169697/darren...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7387,Ryan Giles,67.0,68.0,NaN,62.0,66.0,55.0,62.0,50.0,56.0,...,49.0,41.0,8.0,14.0,6.0,5.0,8.0,Wolves,fifa23,https://www.fifaindex.com/player/243608/ryan-g...
7388,Rúben Neves,82.0,75.0,NaN,77.0,79.0,82.0,81.0,62.0,80.0,...,76.0,82.0,8.0,16.0,12.0,10.0,10.0,Wolves,fifa23,https://www.fifaindex.com/player/224293/r%C3%B...
7389,Saša Kalajdžić,78.0,74.0,NaN,47.0,46.0,44.0,78.0,81.0,34.0,...,57.0,73.0,14.0,7.0,6.0,13.0,15.0,Wolves,fifa23,https://www.fifaindex.com/player/239901/sa%C5%...
7390,Theo Corbeanu,66.0,71.0,NaN,45.0,49.0,40.0,57.0,61.0,39.0,...,55.0,50.0,10.0,7.0,6.0,9.0,7.0,Wolves,fifa23,https://www.fifaindex.com/player/258758/theo-c...
7391,Toti Gomes,62.0,58.0,NaN,73.0,73.0,72.0,72.0,56.0,74.0,...,45.0,42.0,5.0,11.0,6.0,12.0,10.0,Wolves,fifa23,https://www.fifaindex.com/player/258607/toti-g...

In [101]:
# Now that we have the corresponding urls to each player that have nan values in their stats, we can rerun the scraping function for those players
# Step 1: Identify players with missing values
# Get list of columns with NaN values
nan_columns = players_with_nan['Column'].tolist()

# Identify rows (players) where any of those columns are NaN
nan_players = merged_with_url[merged_with_url['Player URL'].notna() & merged_with_url['Player Name'].notna()]
nan_players = nan_players[nan_players[nan_columns].isna().any(axis=1)]

# Step 2: Re-scrape those players
updated_stats = pd.DataFrame()

for _, row in nan_players.iterrows():
    player_url = row['Player URL']
    player_name = row['Player Name']
    version = row['Version']
    team_name = row['Team Name']
    print(f"🔄 Rescraping: {player_name}")
    try:
        df = scrape_sofifa_player_stats(player_url, team_name, version)
        df['Player Name'] = player_name
        df['Team Name'] = row['Team Name']
        df['Version'] = row['Version']
        updated_stats = pd.concat([updated_stats, df], ignore_index=True)
    except Exception as e:
        print(f"❌ Error for {player_name}: {e}")
        continue

🔄 Rescraping: Adam Smith
🔄 Rescraping: Antoine Semenyo
🔄 Rescraping: Chris Mepham
🔄 Rescraping: Dango Ouattara
🔄 Rescraping: Darren Randolph
🔄 Rescraping: David Brooks
🔄 Rescraping: Dominic Sadi
🔄 Rescraping: Dominic Solanke
🔄 Rescraping: Emiliano Marcondes
🔄 Rescraping: Gavin Kilkenny
🔄 Rescraping: Hamed Traorè
🔄 Rescraping: Illia Zabarnyi
🔄 Rescraping: Ionuț Andrei RaduL
🔄 Rescraping: Jaidon Anthony
🔄 Rescraping: Jamal Lowe
🔄 Rescraping: James Hill
🔄 Rescraping: Joe Rothwell
🔄 Rescraping: Justin Kluivert
🔄 Rescraping: Kieffer Moore
🔄 Rescraping: Lewis Cook
🔄 Rescraping: Lloyd Kelly
🔄 Rescraping: Marcos Senesi
🔄 Rescraping: Marcus Tavernier
🔄 Rescraping: Mark Travers
🔄 Rescraping: Milos Kerkez
🔄 Rescraping: Nathan Moriah-Welsh
🔄 Rescraping: Neto
🔄 Rescraping: Owen Bevan
🔄 Rescraping: Philip Billing
🔄 Rescraping: Romain Faivre
🔄 Rescraping: Ryan Christie
🔄 Rescraping: Ryan Fredericks
🔄 Rescraping: Will Dennis
🔄 Rescraping: Adam Smith
🔄 Rescraping: Antoine Semenyo
🔄 Rescraping: Ben Pearson
🔄 Rescraping: Chris Mepham
🔄 Rescraping: Christian Saydee
🔄 Rescraping: Dango Ouattara
🔄 Rescraping: Darren Randolph
🔄 Rescraping: David Brooks
🔄 Rescraping: Dominic Sadi
🔄 Rescraping: Dominic Solanke
🔄 Rescraping: Emiliano Marcondes
🔄 Rescraping: Gavin Kilkenny
🔄 Rescraping: Hamed TraorèL
🔄 Rescraping: Illia Zabarnyi
🔄 Rescraping: Jack Stacey
🔄 Rescraping: Jack StephensL
🔄 Rescraping: Jaidon Anthony
🔄 Rescraping: Jamal Lowe
🔄 Rescraping: James Hill
🔄 Rescraping: Jefferson Lerma
🔄 Rescraping: Joe Rothwell
🔄 Rescraping: Jordan Zemura
🔄 Rescraping: Junior Stanislas
🔄 Rescraping: Kieffer Moore
🔄 Rescraping: Lewis Cook
🔄 Rescraping: Lloyd Kelly
🔄 Rescraping: Marcos Senesi
🔄 Rescraping: Marcus Tavernier
🔄 Rescraping: Mark Travers
🔄 Rescraping: Matías Viña
🔄 Rescraping: Nathan Moriah-Welsh
🔄 Rescraping: Neto
🔄 Rescraping: Owen Bevan
🔄 Rescraping: Philip Billing
🔄 Rescraping: Ryan Christie
🔄 Rescraping: Ryan Fredericks
🔄 Rescraping: Siriki Dembélé
🔄 Rescraping: Aaron Ramsdale
🔄 Rescraping: Albert Sambi Lokonga
🔄 Rescraping: Benjamin White
🔄 Rescraping: Brooke Norton-Cuffy
🔄 Rescraping: Bukayo Saka
🔄 Rescraping: Charlie Patino
🔄 Rescraping: Cédric
🔄 Rescraping: Cătălin Cîrjan
🔄 Rescraping: Declan Rice
🔄 Rescraping: Eddie Nketiah
🔄 Rescraping: Emile Smith Rowe
🔄 Rescraping: Folarin Balogun
🔄 Rescraping: Fábio Vieira
🔄 Rescraping: Gabriel
🔄 Rescraping: Gabriel Jesus
🔄 Rescraping: Gabriel Martinelli
🔄 Rescraping: Jakub Kiwior
🔄 Rescraping: Jorginho
🔄 Rescraping: Jurriën Timber
🔄 Rescraping: Kai Havertz
🔄 Rescraping: Kieran Tierney
🔄 Rescraping: Leandro Trossard
🔄 Rescraping: Marquinhos
🔄 Rescraping: Martin Ødegaard
🔄 Rescraping: Mauro Bandeira
🔄 Rescraping: Mika Biereth
🔄 Rescraping: Mohamed Elneny
🔄 Rescraping: Nicolas Pépé
🔄 Rescraping: Nuno Tavares
🔄 Rescraping: Oleksandr Zinchenko
🔄 Rescraping: Reiss Nelson
🔄 Rescraping: Rob Holding
🔄 Rescraping: Rúnar Alex Rúnarsson
🔄 Rescraping: Takehiro Tomiyasu
🔄 Rescraping: Thomas Partey
🔄 Rescraping: William Saliba
🔄 Rescraping: Aaron Ramsey
🔄 Rescraping: Ainsley Maitland-Niles
🔄 Rescraping: Alex Iwobi
🔄 Rescraping: Alex Oxlade-Chamberlain
🔄 Rescraping: Alexis Sánchez
🔄 Rescraping: Calum Chambers
🔄 Rescraping: Carl Jenkinson
🔄 Rescraping: Chuba Akpom
🔄 Rescraping: Daniel Crowley
🔄 Rescraping: Danny Welbeck
🔄 Rescraping: David Ospina
🔄 Rescraping: Donyell Malen
🔄 Rescraping: Emiliano Martinez
🔄 Rescraping: Francis Coquelin
🔄 Rescraping: Gabriel
🔄 Rescraping: Glen Kamara
🔄 Rescraping: Héctor Bellerín
🔄 Rescraping: Isaac Hayden
🔄 Rescraping: Jack Wilshere
🔄 Rescraping: Jeff Reine-Adelaïde
🔄 Rescraping: Joel Campbell
🔄 Rescraping: Jon Toral
🔄 Rescraping: Julio Pleguezuelo
🔄 Rescraping: Kieran Gibbs
🔄 Rescraping: Krystian Bielik
🔄 Rescraping: Laurent Koscielny
🔄 Rescraping: Marcus McGuane
🔄 Rescraping: Mathieu Flamini
🔄 Rescraping: Matt Macey
🔄 Rescraping: Mesut Özil
🔄 Rescraping: Mohamed Elneny
🔄 Rescraping: Nacho Monreal
🔄 Rescraping: Olivier Giroud
🔄 Rescraping: Per Mertesacker
🔄 Rescraping: Petr Čech
🔄 Rescraping: Santi Cazorla
🔄 Rescraping: Serge Gnabry
🔄 Rescraping: Tafari Moore
🔄 Rescraping: Theo Walcott
🔄 Rescraping: Tomáš Rosický
🔄 Rescraping: Wellington Silva
🔄 Rescraping: Yaya Sanogo
🔄 Rescraping: Danny Welbeck
🔄 Rescraping: William Saliba
🔄 Rescraping: Aaron Ramsdale
🔄 Rescraping: Ainsley Maitland-Niles
🔄 Rescraping: Albert Sambi Lokonga
🔄 Rescraping: Amario Cozier-Duberry
🔄 Rescraping: Arthur Okonkwo
🔄 Rescraping: Auston Trusty
🔄 Rescraping: Benjamin White
🔄 Rescraping: Brooke Norton-Cuffy
🔄 Rescraping: Bukayo Saka
🔄 Rescraping: Charlie Patino
🔄 Rescraping: Cédric
🔄 Rescraping: Cătălin Cîrjan
🔄 Rescraping: Eddie Nketiah
🔄 Rescraping: Emile Smith Rowe
🔄 Rescraping: Folarin Balogun
🔄 Rescraping: Fábio Vieira
🔄 Rescraping: Gabriel
🔄 Rescraping: Gabriel Jesus
🔄 Rescraping: Gabriel Martinelli
🔄 Rescraping: George Lewis
🔄 Rescraping: Granit Xhaka
🔄 Rescraping: Jakub Kiwior
🔄 Rescraping: Joel Ideho
🔄 Rescraping: Jorginho
🔄 Rescraping: Karl Hein
🔄 Rescraping: Kieran Tierney
🔄 Rescraping: Leandro Trossard
🔄 Rescraping: Lino Sousa
🔄 Rescraping: Marquinhos
🔄 Rescraping: Martin Ødegaard
🔄 Rescraping: Matt Turner
🔄 Rescraping: Matthew Smith
🔄 Rescraping: Mohamed Elneny
🔄 Rescraping: Nicolas Pépé
🔄 Rescraping: Nuno Tavares
🔄 Rescraping: Oleksandr Zinchenko
🔄 Rescraping: Pablo Marí
🔄 Rescraping: Reiss Nelson
🔄 Rescraping: Rob Holding
🔄 Rescraping: Ryan Alebiosu
🔄 Rescraping: Rúnar Alex Rúnarsson
🔄 Rescraping: Salah-Eddine Oulad M'Hand
🔄 Rescraping: Takehiro Tomiyasu
🔄 Rescraping: Thomas Partey
🔄 Rescraping: William Saliba
🔄 Rescraping: Aaron Ramsey
🔄 Rescraping: Ben Chrisene
🔄 Rescraping: Bertrand Traoré
🔄 Rescraping: Boubacar Kamara
🔄 Rescraping: Caleb Chukwuemeka
🔄 Rescraping: Calum Chambers
🔄 Rescraping: Cameron Archer
🔄 Rescraping: Coutinho
🔄 Rescraping: Diego Carlos
🔄 Rescraping: Douglas Luiz
🔄 Rescraping: Emiliano Buendía
🔄 Rescraping: Emiliano Martínez
🔄 Rescraping: Ezri Konsa
🔄 Rescraping: Finn Azaz
🔄 Rescraping: Jacob Ramsey
🔄 Rescraping: Jaden Philogene
🔄 Rescraping: Jhon Durán
🔄 Rescraping: John McGinn
🔄 Rescraping: Joshua Feeney
🔄 Rescraping: Kaine Kesler-Hayden
🔄 Rescraping: Keinan Davis
🔄 Rescraping: Kortney Hause
🔄 Rescraping: Lamare Bogarde
🔄 Rescraping: Leander Dendoncker
🔄 Rescraping: Leon Bailey
🔄 Rescraping: Louie Barry
🔄 Rescraping: Lucas Digne
🔄 Rescraping: Matty Cash
🔄 Rescraping: Morgan Sanson
🔄 Rescraping: Moussa Diaby
🔄 Rescraping: Ollie Watkins
🔄 Rescraping: Pau Torres
🔄 Rescraping: Robin Olsen
🔄 Rescraping: Tim Iroegbunam
🔄 Rescraping: Tyrone Mings
🔄 Rescraping: Viljami Sinisalo
🔄 Rescraping: Youri Tielemans
🔄 Rescraping: Álex Moreno
🔄 Rescraping: Adama
🔄 Rescraping: Alan Hutton
🔄 Rescraping: Aly Cissokho
🔄 Rescraping: André Green
🔄 Rescraping: Ashley Westwood
🔄 Rescraping: Benjamin Siegrist
🔄 Rescraping: Brad Guzan
🔄 Rescraping: Bradley Watkins
🔄 Rescraping: Callum Robinson
🔄 Rescraping: Carles Gil
🔄 Rescraping: Carlos Sánchez
🔄 Rescraping: Charles N'Zogbia
🔄 Rescraping: Ciaran Clark
🔄 Rescraping: Corey Blackett-Taylor
🔄 Rescraping: Easah Suliman
🔄 Rescraping: Gabriel Agbonlahor
🔄 Rescraping: Gary Gardner
🔄 Rescraping: Idrissa Gueye
🔄 Rescraping: Jack Grealish
🔄 Rescraping: Janoi Donacien
🔄 Rescraping: Jed Steer
🔄 Rescraping: Jerell Sellars
🔄 Rescraping: Joe Bennett
🔄 Rescraping: Joleon Lescott
🔄 Rescraping: Jordan Amavi
🔄 Rescraping: Jordan Ayew
🔄 Rescraping: Jordan Lyden
🔄 Rescraping: Jordan Veretout
🔄 Rescraping: Jores Okore
🔄 Rescraping: Keinan Davis
🔄 Rescraping: Kevin Toner
🔄 Rescraping: Kieran Richardson
🔄 Rescraping: Leandro Bacuna
🔄 Rescraping: Libor Kozák
🔄 Rescraping: Mark Bunn
🔄 Rescraping: Micah Richards
🔄 Rescraping: Nathan Baker
🔄 Rescraping: Niall Mason
🔄 Rescraping: Riccardo Calder
🔄 Rescraping: Rudy Gestede
🔄 Rescraping: Rushian Hepburn-Murphy
🔄 Rescraping: Scott Sinclair
🔄 Rescraping: Matt Targett
🔄 Rescraping: Aaron Ramsey
🔄 Rescraping: Ashley Young
🔄 Rescraping: Ben Chrisene
🔄 Rescraping: Bertrand Traoré
🔄 Rescraping: Boubacar Kamara
🔄 Rescraping: Caleb Chukwuemeka
🔄 Rescraping: Calum Chambers
🔄 Rescraping: Cameron Archer
🔄 Rescraping: Coutinho
🔄 Rescraping: Diego Carlos
🔄 Rescraping: Douglas Luiz
🔄 Rescraping: Emiliano Buendía
🔄 Rescraping: Emiliano Martínez
🔄 Rescraping: Ezri Konsa
🔄 Rescraping: Finn Azaz
🔄 Rescraping: Hayden Lindley
🔄 Rescraping: Jacob Ramsey
🔄 Rescraping: Jaden Philogene
🔄 Rescraping: Jed Steer
🔄 Rescraping: Jhon Durán
🔄 Rescraping: John McGinn
🔄 Rescraping: Joshua Feeney
🔄 Rescraping: Kaine Kesler-Hayden
🔄 Rescraping: Keinan Davis
🔄 Rescraping: Kortney Hause
🔄 Rescraping: Lamare Bogarde
🔄 Rescraping: Leander Dendoncker
🔄 Rescraping: Leon Bailey
🔄 Rescraping: Louie Barry
🔄 Rescraping: Lucas Digne
🔄 Rescraping: Marvelous Nakamba
🔄 Rescraping: Matty Cash
🔄 Rescraping: Morgan Sanson
🔄 Rescraping: Oliwier Zych
🔄 Rescraping: Ollie Watkins
🔄 Rescraping: Robin Olsen
🔄 Rescraping: Rory Wilson
🔄 Rescraping: Sil Swinkels
🔄 Rescraping: Tim Iroegbunam
🔄 Rescraping: Tommi O'Reilly
🔄 Rescraping: Tyrone Mings
🔄 Rescraping: Viljami Sinisalo
🔄 Rescraping: Wesley
🔄 Rescraping: Álex Moreno
🔄 Rescraping: Adam Federici
🔄 Rescraping: Adam Smith
🔄 Rescraping: Andrew Surman
🔄 Rescraping: Artur Boruc
🔄 Rescraping: Baily Cargill
🔄 Rescraping: Benik Afobe
🔄 Rescraping: Brandon Goodship
🔄 Rescraping: Callum Wilson
🔄 Rescraping: Charlie Daniels
🔄 Rescraping: Dan Gosling
🔄 Rescraping: Eunan O'Kane
🔄 Rescraping: Glenn Murray
🔄 Rescraping: Harry Arter
🔄 Rescraping: Harry Cornick
🔄 Rescraping: Jack Simpson
🔄 Rescraping: Jayden Stockley
🔄 Rescraping: Joe Quigley
🔄 Rescraping: Jonathan Muleba
🔄 Rescraping: Jordan Lee
🔄 Rescraping: Josh Wakefield
🔄 Rescraping: Joshua King
🔄 Rescraping: Juan Manuel Iturbe
🔄 Rescraping: Junior Stanislas
🔄 Rescraping: Lee Tomlin
🔄 Rescraping: Lewis Grabban
🔄 Rescraping: Marc Pugh
🔄 Rescraping: Matt Ritchie
🔄 Rescraping: Matthew Butcher
🔄 Rescraping: Max Gradel
🔄 Rescraping: Rhoys Wiggins
🔄 Rescraping: Ryan Allsop
🔄 Rescraping: Ryan Fraser
🔄 Rescraping: Shaun MacDonald
🔄 Rescraping: Simon Francis
🔄 Rescraping: Steve Cook
🔄 Rescraping: Stéphane Zubar
🔄 Rescraping: Sylvain Distin
🔄 Rescraping: Tokelo Rantie
🔄 Rescraping: Tommy Elphick
🔄 Rescraping: Tyrone Mings
🔄 Rescraping: Aaron Hickey
🔄 Rescraping: Ben Mee
🔄 Rescraping: Bryan Mbeumo
🔄 Rescraping: Charlie Goode
🔄 Rescraping: Christian Nørgaard
🔄 Rescraping: Daniel Oyegoke
🔄 Rescraping: David Raya
🔄 Rescraping: Ellery Balcombe
🔄 Rescraping: Ethan Brierley
🔄 Rescraping: Ethan Pinnock
🔄 Rescraping: Fin Stevens
🔄 Rescraping: Frank Onyeka
🔄 Rescraping: Josh Dasilva
🔄 Rescraping: Keane Lewis-Potter
🔄 Rescraping: Kevin Schade
🔄 Rescraping: Kim Ji Soo
🔄 Rescraping: Kristoffer Ajer
🔄 Rescraping: Mads Bech Sørensen
🔄 Rescraping: Mads Roerslev
🔄 Rescraping: Mark Flekken
🔄 Rescraping: Mathias Jensen
🔄 Rescraping: Matthew Cox
🔄 Rescraping: Michael Olakigbe
🔄 Rescraping: Mikkel Damsgaard
🔄 Rescraping: Myles Peart-Harris
🔄 Rescraping: Nathan Collins
🔄 Rescraping: Nathan Young-Coombes
🔄 Rescraping: Paris Maghoma
🔄 Rescraping: Rico Henry
🔄 Rescraping: Ryan Trevitt
🔄 Rescraping: Sergi Canós
🔄 Rescraping: Shandon Baptiste
🔄 Rescraping: Thomas Strakosha
🔄 Rescraping: Tristan Crama
🔄 Rescraping: Vitaly Janelt
🔄 Rescraping: Yehor Yarmoliuk
🔄 Rescraping: Yoane Wissa
🔄 Rescraping: Zanka
🔄 Rescraping: Aaron Hickey
🔄 Rescraping: Aaron Pressley
🔄 Rescraping: Alex Gilbert
🔄 Rescraping: Ben Mee
🔄 Rescraping: Bryan Mbeumo
🔄 Rescraping: Charlie Goode
🔄 Rescraping: Christian Nørgaard
🔄 Rescraping: Daniel Oyegoke
🔄 Rescraping: David Raya
🔄 Rescraping: Ellery Balcombe
🔄 Rescraping: Ethan Pinnock
🔄 Rescraping: Fin Stevens
🔄 Rescraping: Frank Onyeka
🔄 Rescraping: Halil İbrahim Dervişoğlu
🔄 Rescraping: Ivan Toney
🔄 Rescraping: Josh Dasilva
🔄 Rescraping: Keane Lewis-Potter
🔄 Rescraping: Kevin SchadeL
🔄 Rescraping: Kristoffer Ajer
🔄 Rescraping: Lachlan Brook
🔄 Rescraping: Mads Bech Sørensen
🔄 Rescraping: Mads Bidstrup
🔄 Rescraping: Mads Roerslev
🔄 Rescraping: Mathias Jensen
🔄 Rescraping: Matthew Cox
🔄 Rescraping: Mikkel Damsgaard
🔄 Rescraping: Myles Peart-Harris
🔄 Rescraping: Nathan Young-Coombes
🔄 Rescraping: Paris Maghoma
🔄 Rescraping: Pontus Jansson
🔄 Rescraping: Rico Henry
🔄 Rescraping: Ryan Trevitt
🔄 Rescraping: Saman Ghoddos
🔄 Rescraping: Shandon Baptiste
🔄 Rescraping: Tariqe Fosu
🔄 Rescraping: Thomas Strakosha
🔄 Rescraping: Tristan Crama
🔄 Rescraping: Vitaly Janelt
🔄 Rescraping: Yehor Yarmoliuk
🔄 Rescraping: Yoane Wissa
🔄 Rescraping: Zanka
🔄 Rescraping: Aaron Connolly
🔄 Rescraping: Abdallah Sima
🔄 Rescraping: Adam Lallana
🔄 Rescraping: Adam Webster
🔄 Rescraping: Alexis Mac Allister
🔄 Rescraping: Andi Zeqiri
🔄 Rescraping: Billy Gilmour
🔄 Rescraping: Cameron Peupion
🔄 Rescraping: Carl Rushworth
🔄 Rescraping: Danny Welbeck
🔄 Rescraping: Deniz Undav
🔄 Rescraping: Ed Turns
🔄 Rescraping: Evan Ferguson
🔄 Rescraping: Facundo Buonanotte
🔄 Rescraping: Haydon Roberts
🔄 Rescraping: Jack Hinchy
🔄 Rescraping: Jakub Moder
🔄 Rescraping: Jamie Mullins
🔄 Rescraping: Jan Paul van Hecke
🔄 Rescraping: Jason Steele
🔄 Rescraping: Jensen Weir
🔄 Rescraping: Jeremy Sarmiento
🔄 Rescraping: Joël Veltman
🔄 Rescraping: Julio César Enciso
🔄 Rescraping: Kacper Kozłowski
🔄 Rescraping: Kaoru Mitoma
🔄 Rescraping: Kjell Scherpen
🔄 Rescraping: Levi ColwillL
🔄 Rescraping: Lewis Dunk
🔄 Rescraping: Marc Leonard
🔄 Rescraping: Michał Karbownik
🔄 Rescraping: Moisés Caicedo
🔄 Rescraping: Odel Offiah
🔄 Rescraping: Pascal Groß
🔄 Rescraping: Pervis Estupiñán
🔄 Rescraping: Reda Khadra
🔄 Rescraping: Robert Sánchez
🔄 Rescraping: Simon Adingra
🔄 Rescraping: Solly March
🔄 Rescraping: Steven Alzate
🔄 Rescraping: Tariq Lamptey
🔄 Rescraping: Taylor Richards
🔄 Rescraping: Teddy Jenks
🔄 Rescraping: Tom McGill
🔄 Rescraping: Yasin Ayari
🔄 Rescraping: Abdallah Sima
🔄 Rescraping: Adam Lallana
🔄 Rescraping: Adam Webster
🔄 Rescraping: Andi Zeqiri
🔄 Rescraping: Bart Verbruggen
🔄 Rescraping: Billy Gilmour
🔄 Rescraping: Cameron Peupion
🔄 Rescraping: Carl Rushworth
🔄 Rescraping: Danny Welbeck
🔄 Rescraping: Deniz Undav
🔄 Rescraping: Ed Turns
🔄 Rescraping: Evan Ferguson
🔄 Rescraping: Facundo Buonanotte
🔄 Rescraping: Igor
🔄 Rescraping: Jack Hinshelwood
🔄 Rescraping: Jakub Moder
🔄 Rescraping: James Beadle
🔄 Rescraping: James Furlong
🔄 Rescraping: James Milner
🔄 Rescraping: Jan Paul van Hecke
🔄 Rescraping: Jason Steele
🔄 Rescraping: Jensen Weir
🔄 Rescraping: Jeremy Sarmiento
🔄 Rescraping: João Pedro
🔄 Rescraping: Joël Veltman
🔄 Rescraping: Julio César Enciso
🔄 Rescraping: Kacper Kozłowski
🔄 Rescraping: Kaoru Mitoma
🔄 Rescraping: Kjell Scherpen
🔄 Rescraping: Lewis Dunk
🔄 Rescraping: Mahmoud Dahoud
🔄 Rescraping: Marc Leonard
🔄 Rescraping: Moisés Caicedo
🔄 Rescraping: Odel Offiah
🔄 Rescraping: Pascal Groß
🔄 Rescraping: Pervis Estupiñán
🔄 Rescraping: Simon Adingra
🔄 Rescraping: Solly March
🔄 Rescraping: Steven Alzate
🔄 Rescraping: Tariq Lamptey
🔄 Rescraping: Tom McGill
🔄 Rescraping: Yasin Ayari
🔄 Rescraping: Bernardo
🔄 Rescraping: Ameen Al Dakhil
🔄 Rescraping: Anass Zaroury
🔄 Rescraping: Arijanet Murić
🔄 Rescraping: Bailey Peacock-Farrell
🔄 Rescraping: Benn Ward
🔄 Rescraping: Benson Manuel
🔄 Rescraping: CJ Egan-Riley
🔄 Rescraping: Charlie Taylor
🔄 Rescraping: Connor Roberts
🔄 Rescraping: Dara Costelloe
🔄 Rescraping: Dara O'Shea
🔄 Rescraping: Darko Churlinov
🔄 Rescraping: Denis Franchi
🔄 Rescraping: Hjalmar Ekdal
🔄 Rescraping: Jack Cork
🔄 Rescraping: Jacob Bruun LarsenL
🔄 Rescraping: James Trafford
🔄 Rescraping: Jay Rodriguez
🔄 Rescraping: Jez Davies
🔄 Rescraping: Jordan Beyer
🔄 Rescraping: Josh Brownhill
🔄 Rescraping: Josh Cullen
🔄 Rescraping: Jóhann Berg Guðmundsson
🔄 Rescraping: Lawrence Vigouroux
🔄 Rescraping: Lewis Richardson
🔄 Rescraping: Luca Warrick Koleosho
🔄 Rescraping: Luke McNally
🔄 Rescraping: Lyle Foster
🔄 Rescraping: Marcel Lewis
🔄 Rescraping: Michael Mellon
🔄 Rescraping: Michael Obafemi
🔄 Rescraping: Nathan Redmond
🔄 Rescraping: Owen Dodgson
🔄 Rescraping: Samuel Bastien
🔄 Rescraping: Scott Twine
🔄 Rescraping: Vitinho
🔄 Rescraping: Wout Weghorst
🔄 Rescraping: Zeki Amdouni
🔄 Rescraping: Andrey Santos
🔄 Rescraping: Armando Broja
🔄 Rescraping: Axel Disasi
🔄 Rescraping: Bashir Humphreys
🔄 Rescraping: Ben Chilwell
🔄 Rescraping: Benoît Badiashile
🔄 Rescraping: Callum Hudson-Odoi
🔄 Rescraping: Carney Chukwuemeka
🔄 Rescraping: Cesare Casadei
🔄 Rescraping: Charlie Webster
🔄 Rescraping: Christopher Nkunku
🔄 Rescraping: Conor Gallagher
🔄 Rescraping: Cucurella
🔄 Rescraping: David Datro Fofana
🔄 Rescraping: Dion Rankine
🔄 Rescraping: Enzo Fernández
🔄 Rescraping: Gabriel Slonina
🔄 Rescraping: Hakim Ziyech
🔄 Rescraping: Ian Maatsen
🔄 Rescraping: Kepa
🔄 Rescraping: Lesley Ugochukwu
🔄 Rescraping: Levi Colwill
🔄 Rescraping: Lewis Hall
🔄 Rescraping: Malang Sarr
🔄 Rescraping: Malo Gusto
🔄 Rescraping: Marcus Bettinelli
🔄 Rescraping: Mykhailo Mudryk
🔄 Rescraping: Nicolas Jackson
🔄 Rescraping: Noni Madueke
🔄 Rescraping: Omari Hutchinson
🔄 Rescraping: Raheem Sterling
🔄 Rescraping: Reece James
🔄 Rescraping: Robert Sánchez
🔄 Rescraping: Romelu Lukaku
🔄 Rescraping: Thiago Silva
🔄 Rescraping: Trevoh Chalobah
🔄 Rescraping: Wesley Fofana
🔄 Rescraping: Abdul Rahman Baba
🔄 Rescraping: Alexandre Pato
🔄 Rescraping: Andreas Christensen
🔄 Rescraping: Asmir Begović
🔄 Rescraping: Azpilicueta
🔄 Rescraping: Bertrand Traoré
🔄 Rescraping: Bradley Collins
🔄 Rescraping: Branislav Ivanović
🔄 Rescraping: Cesc Fàbregas
🔄 Rescraping: Charlie Colkett
🔄 Rescraping: Charly Musonda
🔄 Rescraping: Cristian Manea
🔄 Rescraping: Diego Costa
🔄 Rescraping: Eden Hazard
🔄 Rescraping: Falcao
🔄 Rescraping: Fikayo Tomori
🔄 Rescraping: Gary Cahill
🔄 Rescraping: Jake Clarke-Salter
🔄 Rescraping: Joao Rodríguez
🔄 Rescraping: John Obi Mikel
🔄 Rescraping: John Swift
🔄 Rescraping: John Terry
🔄 Rescraping: Kasey Palmer
🔄 Rescraping: Kenedy
🔄 Rescraping: Kurt Zouma
🔄 Rescraping: Lewis Baker
🔄 Rescraping: Loïc Rémy
🔄 Rescraping: Lucas Piazon
🔄 Rescraping: Marco Amelia
🔄 Rescraping: Marco van Ginkel
🔄 Rescraping: Matt Miazga
🔄 Rescraping: Michael Hector
🔄 Rescraping: Nathan
🔄 Rescraping: Nathan Aké
🔄 Rescraping: Nemanja Matić
🔄 Rescraping: Ola Aina
🔄 Rescraping: Oscar
🔄 Rescraping: Patrick Bamford
🔄 Rescraping: Pedro
🔄 Rescraping: Ruben Loftus-Cheek
🔄 Rescraping: Tammy Abraham
🔄 Rescraping: Thibaut Courtois
🔄 Rescraping: Tomáš Kalas
🔄 Rescraping: Victor Moses
🔄 Rescraping: Willian
🔄 Rescraping: Armando Broja
🔄 Rescraping: Azpilicueta
🔄 Rescraping: Baba Rahman
🔄 Rescraping: Ben Chilwell
🔄 Rescraping: Benoît Badiashile
🔄 Rescraping: Callum Hudson-Odoi
🔄 Rescraping: Carney Chukwuemeka
🔄 Rescraping: Christian Pulisic
🔄 Rescraping: Conor Gallagher
🔄 Rescraping: Cucurella
🔄 Rescraping: David Datro Fofana
🔄 Rescraping: Denis ZakariaL
🔄 Rescraping: Dujon Sterling
🔄 Rescraping: Enzo Fernández
🔄 Rescraping: Ethan Ampadu
🔄 Rescraping: Hakim Ziyech
🔄 Rescraping: Ian Maatsen
🔄 Rescraping: Jamie Cumming
🔄 Rescraping: João FélixL
🔄 Rescraping: Kai Havertz
🔄 Rescraping: Kalidou Koulibaly
🔄 Rescraping: Kepa
🔄 Rescraping: Levi Colwill
🔄 Rescraping: Lewis Hall
🔄 Rescraping: Malang Sarr
🔄 Rescraping: Malo Gusto
🔄 Rescraping: Marcus Bettinelli
🔄 Rescraping: Mason Mount
🔄 Rescraping: Mateo Kovačić
🔄 Rescraping: Mykhailo Mudryk
🔄 Rescraping: N'Golo Kanté
🔄 Rescraping: Noni Madueke
🔄 Rescraping: Omari Hutchinson
🔄 Rescraping: Pierre-Emerick Aubameyang
🔄 Rescraping: Raheem Sterling
🔄 Rescraping: Reece James
🔄 Rescraping: Romelu Lukaku
🔄 Rescraping: Ruben Loftus-Cheek
🔄 Rescraping: Thiago Silva
🔄 Rescraping: Tiemoué Bakayoko
🔄 Rescraping: Tino Anjorin
🔄 Rescraping: Trevoh Chalobah
🔄 Rescraping: Wesley Fofana
🔄 Rescraping: Édouard Mendy
🔄 Rescraping: Cheick Doucouré
🔄 Rescraping: Chris Richards
🔄 Rescraping: David Ozoh
🔄 Rescraping: Eberechi Eze
🔄 Rescraping: Guaita
🔄 Rescraping: Jack Wells-Morrison
🔄 Rescraping: Jake O'Brien
🔄 Rescraping: James Tomkins
🔄 Rescraping: Jaïro Riedewald
🔄 Rescraping: Jean-Philippe Mateta
🔄 Rescraping: Jefferson Lerma
🔄 Rescraping: Jeffrey Schlupp
🔄 Rescraping: Jesurun Rak-Sakyi
🔄 Rescraping: Joachim Andersen
🔄 Rescraping: Joe Whitworth
🔄 Rescraping: Joel Ward
🔄 Rescraping: Jordan Ayew
🔄 Rescraping: Killian Phillips
🔄 Rescraping: Kofi Balmer

In [103]:
nan_analysis(updated_stats)

            Column  Percentage of NaN Values  Number of NaN Values
35  Sprint Speed 1                 99.958695                  2420
34       Stamina 6                 99.958695                  2420
10       Composure                 33.292028                   806
18    Sprint Speed                  0.247831                     6
20         Jumping                  0.206526                     5
26         FK Acc.                  0.206526                     5
21         Heading                  0.206526                     5
24      Long Shots                  0.206526                     5
19         Agility                  0.206526                     5
25           Curve                  0.206526                     5
17         Balance                  0.206526                     5
16        Strength                  0.206526                     5
15         Stamina                  0.206526                     5
27       Penalties                  0.206526                     5
23       Finishing                  0.206526                     5
28         Volleys                  0.206526                     5
29  GK Positioning                  0.206526                     5
30       GK Diving                  0.206526                     5
31     GK Handling                  0.206526                     5
32      GK Kicking                  0.206526                     5
33     GK Reflexes                  0.206526                     5
22      Shot Power                  0.206526                     5
2          Marking                  0.165221                     4
4     Stand Tackle                  0.165221                     4
5       Aggression                  0.165221                     4
1        Dribbling                  0.165221                     4
14    Acceleration                  0.165221                     4
13       Long Pass                  0.165221                     4
12      Short Pass                  0.165221                     4
11        Crossing                  0.165221                     4
3     Slide Tackle                  0.165221                     4
9           Vision                  0.165221                     4
8    Interceptions                  0.165221                     4
7    Att. Position                  0.165221                     4
6        Reactions                  0.165221                     4
0     Ball Control                  0.165221                     4

In [105]:
updated_stats.to_csv("updated_player_stats.csv", index=False)

In [106]:
updated_stats.drop(columns=['Sprint Speed 1', "Stamina 6", "Composure"], inplace=True)

In [123]:
# Set index for clean update logic
#merged_with_url.set_index(['Player Name', 'Team Name', 'Version'], inplace=True)
#updated_stats.set_index(['Player Name', 'Team Name', 'Version'], inplace=True)

# Update only NaN values
for col in updated_stats.columns:
    merged_with_url[col] = merged_with_url[col].combine_first(updated_stats[col])

# Reset index back
merged_with_url.reset_index(inplace=True)

In [127]:
merged_with_url.to_csv("final_player_stats.csv", index=False)

In [10]:
jeremy_doku_link = "https://www.fifaindex.com/player/246420/j%C3%A9r%C3%A9my-doku/fifa24_593/"
#scrape jeremy_doku_link
#Team is Manchester City
#fifa24
jeremy_doku_stats = scrape_sofifa_player_stats(jeremy_doku_link, "Manchester City", "fifa24")
jeremy_doku_stats.insert(0, 'Player Name', 'Jérémy Doku')  # Add name as first column

In [11]:
jeremy_doku_stats

,Player Name,Ball Control 1,Dribbling 2,Marking,Slide Tackle,Stand Tackle,Aggression,Reactions 4,Att. Position,Interceptions,...,FK Acc.,Penalties,Volleys 5,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes,Team,Version
0,Jérémy Doku,77,85,None,25,28,58,74,72,18,...,44,51,59,9,11,10,8,12,Manchester City,fifa24

In [14]:
jeremy_doku_stats.columns

Index(['Player Name', 'Ball Control 1', 'Dribbling 2', 'Marking',
       'Slide Tackle', 'Stand Tackle', 'Aggression', 'Reactions 4',
       'Att. Position', 'Interceptions', 'Vision', 'Composure 1', 'Crossing 2',
       'Short Pass 3', 'Long Pass 2', 'Acceleration', 'Stamina 2',
       'Strength 1', 'Balance', 'Sprint Speed', 'Agility 3', 'Jumping 6',
       'Heading', 'Shot Power 1', 'Finishing 3', 'Long Shots', 'Curve 3',
       'FK Acc.', 'Penalties', 'Volleys 5', 'GK Positioning', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Reflexes', 'Team', 'Version'],
      dtype='object')

In [18]:
"""
['Player Name', 'Ball Control 1', 'Dribbling 2', 'Marking',
       'Slide Tackle', 'Stand Tackle', 'Aggression', 'Reactions 4',
       'Att. Position', 'Interceptions', 'Vision', 'Composure 1', 'Crossing 2',
       'Short Pass 3', 'Long Pass 2', 'Acceleration', 'Stamina 2',
       'Strength 1', 'Balance', 'Sprint Speed', 'Agility 3', 'Jumping 6',
       'Heading', 'Shot Power 1', 'Finishing 3', 'Long Shots', 'Curve 3',
       'FK Acc.', 'Penalties', 'Volleys 5', 'GK Positioning', 'GK Diving',
       'GK Handling', 'GK Kicking', 'GK Reflexes', 'Team', 'Version']
"""
# Rename columns to match the format of merged_with_url, which dont have the numbers at the end
jeremy_doku_stats.rename(columns={
    'Ball Control 1': 'Ball Control',
    'Dribbling 2': 'Dribbling',
    'Reactions 4': 'Reactions',
    'Short Pass 3': 'Short Pass',
    'Long Pass 2': 'Long Pass',
    'Composure 1': 'Composure',
    'Crossing 2': 'Crossing',
    'Stamina 2': 'Stamina',
    'Strength 1': 'Strength',
    'Agility 3': 'Agility',
    'Jumping 6': 'Jumping',
    'Shot Power 1': 'Shot Power',
    'Finishing 3': 'Finishing',
    'Curve 3': 'Curve',
    'Volleys 5': 'Volleys',
    'Team':'Team Name'}, inplace=True)

In [ ]:
merged_with_url = pd.read_csv("Data/final_player_stats.csv")
merged_with_url = pd.concat([merged_with_url, jeremy_doku_stats], ignore_index=True)

In [20]:
merged_with_url = pd.read_csv("Data/final_player_stats.csv")

In [21]:
#add jeremy doku url to the merged_with_url DataFrame
merged_with_url.loc[merged_with_url['Player Name'] == 'Jérémy Doku', 'Player URL'] = jeremy_doku_link

In [23]:
merged_with_url.to_csv("Data/final_player_stats.csv", index=False)